default: true

# Essential rules
MD013: false  # Line length - often too restrictive for technical docs
MD024: false  # Multiple headings with same content - common in technical docs
MD025: false  # Multiple top-level headings - needed for some doc structures
MD033: false  # Inline HTML - often needed for complex formatting
MD034: false  # Bare URL used - common in technical docs
MD040: false  # Fenced code blocks should have language - not always needed
MD041: false  # First line should be heading - not always needed
MD047: false  # Files should end with newline - too strict

# Heading rules
MD001: false  # Heading levels should only increment by one level at a time
MD002: false  # First heading should be a top-level heading
MD003: false  # Heading style
MD022: false  # Headings should be surrounded by blank lines
MD023: false  # Headings must start at the beginning of the line
MD026: false  # Trailing punctuation in heading

# List rules
MD004: false  # Unordered list style
MD005: false  # Inconsistent indentation for list items at the same level
MD006: false  # Consider starting bulleted lists at the beginning of the line
MD007: false  # Unordered list indentation
MD029: false  # Ordered list item prefix
MD030: false  # Spaces after list markers
MD032: false  # Lists should be surrounded by blank lines

# Code block rules
MD031: false  # Fenced code blocks should be surrounded by blank lines
MD046: false  # Code block style
MD048: false  # Code fence style

# Link rules
MD011: false  # Reversed link syntax
MD039: false  # Spaces inside link text
MD042: false  # No empty links
MD051: false  # Link fragments should be valid
MD052: false  # Reference links should be valid

# Style rules
MD009: false  # Trailing spaces
MD010: false  # Hard tabs
MD012: false  # Multiple consecutive blank lines
MD018: false  # No space after hash on atx style heading
MD019: false  # Multiple spaces after hash on atx style heading
MD020: false  # No space inside hashes on closed atx style heading
MD021: false  # Multiple spaces inside hashes on closed atx style heading
MD027: false  # Multiple spaces after blockquote symbol
MD028: false  # Blank line inside blockquote
MD035: false  # Horizontal rule style
MD036: false  # Emphasis used instead of a heading
MD037: false  # Spaces inside emphasis markers
MD038: false  # Spaces inside code span elements
MD044: false  # Proper names should have the correct capitalization
MD045: false  # Images should have alternate text (alt text)
MD049: false  # Emphasis style should be consistent
MD050: false  # Strong style should be consistent
MD053: false  # Link text should not be the same as the link URL
MD058: false  # Blanks around tables

# Other rules
MD014: false  # Dollar signs used before commands without showing output 